# 1-animation
- domain_lora_scale: 1.0
  adapter_lora_path: ""
  # dreambooth_path:   ""
  dreambooth_path:   "models/DreamBooth_LoRA/dynavisionXLAllInOneStylized_release0534bakedvae.safetensors"

  inference_config: "configs/inference/inference-xl.yaml"
  motion_module:    "models/Motion_Module/mm_sdxl.ckpt"

  # controlnet_config: ""
  # controlnet_path:   ""

  H: 512
  W: 512
  seed: [123,234]
  steps: 25
  guidance_scale: 8.5

  # controlnet_image_indexs: [0]
  # controlnet_images:
  #   - "__assets__/demos/image/painting.png"

  prompt:
    - "beautiful nature scene, sunset in a valley, green forest, lake, mountains, snow on mountain tops, winter"
    - "closeup face photo of man in black clothes, night city street, fireworks in background"
  n_prompt:
    - "worst quality, low quality, letterboxed"

